### ISSUE TITLE
Describe mascots for the game

### ISSUE THREAD

**Issue by melofon** [goodlancer-org/typer-miner#1]
Create text definitions of the game mascot (mascots) to be used in the game, in documentation and presentation slides

**Comment by baby-shark-tuturu** [comment]
Mascot:
An anthropomorphic plump mole miner covered in fur, wearing a dirty miner's outfit and a yellow miner's helmet with a headlamp. Large claws, very small eyes, two protruding rectangular teeth. In one hand he holds a massive pickaxe. His clothing is mostly done in shades of brown and yellow.
background:
A large mountain range against the sky and field, with a rock in the foreground on which lies a guitar, all in green and gray tones with a cloudy sky, aspect ratio 16:9
